config/routes.rb
Rails.application.routes.draw do
  resources :sumptoms
  resources :problems
  resources :animals
  resources :categories

end

app/models/sumptom.rb
class Sumptom < ActiveRecord::Base
  belongs_to  :animal
  belongs_to  :problem
end

app/controllers/sumptoms_controller.rb
class SumptomsController < ApplicationController
  before_action :set_sumptom, only: [:show, :edit, :update, :destroy]

  # GET /sumptoms
  # GET /sumptoms.json
  def index
    @sumptoms = Sumptom.all
  end

  # GET /sumptoms/1
  # GET /sumptoms/1.json
  def show
  end

  # GET /sumptoms/new
  def new
    @sumptom = Sumptom.new
  end

  # GET /sumptoms/1/edit
  def edit
  end

  # POST /sumptoms
  # POST /sumptoms.json
  def create
    @sumptom = Sumptom.new(sumptom_params)

    respond_to do |format|
      if @sumptom.save
        format.html { redirect_to @sumptom, notice: 'Sumptom was successfully created.' }
        format.json { render :show, status: :created, location: @sumptom }
      else
        format.html { render :new }
        format.json { render json: @sumptom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sumptoms/1
  # PATCH/PUT /sumptoms/1.json
  def update
    respond_to do |format|
      if @sumptom.update(sumptom_params)
        format.html { redirect_to @sumptom, notice: 'Sumptom was successfully updated.' }
        format.json { render :show, status: :ok, location: @sumptom }
      else
        format.html { render :edit }
        format.json { render json: @sumptom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sumptoms/1
  # DELETE /sumptoms/1.json
  def destroy
    @sumptom.destroy
    respond_to do |format|
      format.html { redirect_to sumptoms_url, notice: 'Sumptom was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sumptom
      @sumptom = Sumptom.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sumptom_params
      params.require(:sumptom).permit(:animal_id, :problem_id)
    end
end

app/helpers/sumptoms_helper.rb
module SumptomsHelper
end

app/views/sumptoms/_form.html.erb
<%= semantic_form_for @sumptom do |f| %>
  <%= f.inputs do %>
    <%= f.input :animal_id %>
    <%= f.input :problem_id %>
  <% end %>

  <%= f.actions do %>
    <%= f.action :submit, :as => :input %>
  <% end %>
<% end %>

app/views/sumptoms/edit.html.erb
<h1>Editing Sumptom</h1>

<%= render 'form' %>

<%= link_to 'Show', @sumptom %> |
<%= link_to 'Back', sumptoms_path %>

app/views/sumptoms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sumptoms</h1>

<table>
  <thead>
    <tr>
      <th>Animal</th>
      <th>Problem</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sumptoms.each do |sumptom| %>
      <tr>
        <td><%= sumptom.animal_id %></td>
        <td><%= sumptom.problem_id %></td>
        <td><%= link_to 'Show', sumptom %></td>
        <td><%= link_to 'Edit', edit_sumptom_path(sumptom) %></td>
        <td><%= link_to 'Destroy', sumptom, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sumptom', new_sumptom_path %>

app/views/sumptoms/new.html.erb
<h1>New Sumptom</h1>

<%= render 'form' %>

<%= link_to 'Back', sumptoms_path %>

app/views/sumptoms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Animal:</strong>
  <%= @sumptom.animal_id %>
</p>

<p>
  <strong>Problem:</strong>
  <%= @sumptom.problem_id %>
</p>

<%= link_to 'Edit', edit_sumptom_path(@sumptom) %> |
<%= link_to 'Back', sumptoms_path %>